# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='coolest guy in town'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_uploaded', to='thanksgiving_recipes_app.User'),
        ),
    ]
