# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0002_auto_20191119_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_has_comments', to='thanksgiving_recipes_app.Recipe')),
                ('comment_on_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_has_comments', to='thanksgiving_recipes_app.Recipe')),
            ],
        ),
    ]
