# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0004_auto_20191120_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
