# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.TextField(default='profile pic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
