# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0006_auto_20191120_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
