# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0010_auto_20191121_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='has_image', to='thanksgiving_recipes_app.User'),
            preserve_default=False,
        ),
    ]
