# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0011_post_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
