# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0012_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='image title'),
            preserve_default=False,
        ),
    ]
