# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0014_remove_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='images/')),
                ('recipe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_has_images', to='thanksgiving_recipes_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='images/')),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_has_image', to='thanksgiving_recipes_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_image',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
