# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0015_auto_20191121_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_has_images', to='thanksgiving_recipes_app.Recipe'),
        ),
    ]
