# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0016_auto_20191121_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='cover',
            field=models.ImageField(height_field='100', upload_to='images/', width_field='100'),
        ),
    ]
