# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_recipes_app', '0017_auto_20191122_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
